### ISSUE TITLE
Failure on tone tag --meta-remove-property recordingdate file.m4b 

### ISSUE THREAD

**Issue by sandreas** [sandreas/tone#15]
The following command does not work:

```bash
tone tag --meta-remove-property recordingdate file.m4b 
```

Probably a Problem with `atldotnet` or a misuse of the internal API

**Comment by sandreas** [comment]
This has to do with #17

Something is fishy with `Track.RecordingDate` and with `Track.Description` when writing or removing `mp4` (`m4a`, `m4b`)

**Comment by advplyr** [comment]
I've tested `--meta-remove-property` for several other properties like album & description for mp3/m4b and it doesn't work.

```
tone tag --meta-remove-property="album" file.m4b
```
output shows it was removed

```
tone dump file.m4b
```
album property remains unchanged

**Comment by sandreas** [comment]
> You could also allow setting meta tags to empty strings.

Yeah unfortunately I found multiple bugs in `spectre.console` (my console library for C#), reported them and was mostly not responding, which frustrated me a bit... [recently someone else also thought that these issues should be fixed](https://github.com/spectreconsole/spectre.console/discussions/1025) and that there is a major misbehaviour in the argument parsing, which I agree with.

So, until these issues are all fixed and the argument parsing works as expected, it is unreliable to use command line parameters in [some edge cases](https://github.com/spectreconsole/spectre.console/discussions/1025#discussioncomment-3936289). That's why I invented the `tone.json` format, which works reliably in all cases I've tested. Using `tone.json` you can also try to set `album: null`, which should delete the field (but that is something I did not fully test yet).

Nevertheless, that issue is definitely gonna be paid attention in the the very near future...

**Comment by advplyr** [comment]
What about the `--meta-remove-property`? The `spectre.console` issues are not related to that bug right?

**Comment by sandreas** [comment]
> What about the --meta-remove-property? The spectre.console issues are not related to that bug right?

Correct. I'll try to fix this next release. same for #32

**Comment by sandreas** [comment]
Mmh I added a new issue describing the problem in atldotnet (see above). The problem is, that I did not find a way to really remove the property in every case, but only setting it to an empty value in case of string.

I implemented the *set to empty*, but I think it would be more accurate, if remove really means remove. Would you mind if I wait with the next release until I get response?

**Comment by advplyr** [comment]
No problem, thanks. The other one that is helpful for using in abs is #29
