### ISSUE TITLE
When auto importing covers, every file gets the same cover image

### ISSUE THREAD

**Issue by CamJN** [sandreas/tone#49]
Using `tone tag --auto-import=covers` on a tree of dirs/audio books to set the cover art, every book winds up with the first image instead of the one in the same dir as it.

**Comment by sandreas** [comment]
Hey, thanks for reporting.

Would you mind providing the whole command you are executing and an example of the used file structure? That would make it a lot easier to reproduce...
Thank you.

**Comment by sandreas** [comment]
Superb, thank you. I'll try to reproduce this in the next days.

**Comment by CamJN** [comment]
Also, I have two files which cause tone to be very slow doing anything with the tags, whereas other much larger files are much faster. I wonder if it is worth opening an issue about that? I'd have to provide you the files via a different means than Github as they are too big to upload to the issue directly.

**Comment by sandreas** [comment]
> Also, I have two files which cause tone to be very slow doing anything with the tags, whereas other much larger files are much faster.

Is probably is a behaviour in `atldotnet`(my main tagging lib). I'll see what I can do and get back to you asap.

**Comment by sandreas** [comment]
Should be fixed in `0.2.0`.
