### ISSUE TITLE
Embedded Picture MimeType...

### ISSUE THREAD

**Issue by gitoss** [sandreas/tone#54]
Embedding an image with "tone --meta-cover-file=image.jpg audio.mp3", works nicely, but the meta tag is "MimeType:image/*" instead of "image/jpeg" (or respective other image types).

Any other tools I ever tried to (including the 2006 metamp3) set this mime type to the image format. I dunno if this has any real life consequences, because extracting the cover with id3-images.exe sets it to .jpg - probably by default?

Using tone release 0.1.5 on Windows.

**Comment by sandreas** [comment]
> Embedding an image with "tone --meta-cover-file=image.jpg audio.mp3"

I never thought of this... this is something we have to discuss with the `atldotnet` maintainer (the tagging lib). As soon as I find the time, I'll go for it.

**Comment by gitoss** [comment]
Thanks for the answers, I was already suspecting I'm barking up the wrong tree because you're mentioning that tone is based on this library. Anyway, I've reported it _somewhere_

**Comment by sandreas** [comment]
Ok, in the next days I will publish the `0.1.8` along with some documentation updates. It should be fixed, because I also upgraded the latest `atldotnet` version.

Please reopen the ticket, if the issue still occurs after testing with `0.1.8`.
