### ISSUE TITLE
Embedded Picture Cover Type...

### ISSUE THREAD

**Issue by gitoss** [sandreas/tone#55]
Embedding an image with "tone --meta-cover-file=image.jpg audio.mp3", works nicely, but no Type is set (not is there a command line for setting it). For mp3 this defaults to "Other" and not "Cover (Front)" like the default in just about any tool I've tried before.

You can check with mediainfo, exiftool, ... and id3-images.exe extracts the file to "other.jpg" and not front_cover.jpg.

Using tone release 0.1.5 on Windows.

**Comment by sandreas** [comment]
Also `atldotnet` maintainer.

**Comment by noidwasavailable** [comment]
Is there any update on this? I tried using tone to add metadata to some files, and the album art is correctly shown for Apple Music, but it isn't shown for Finder and Spotify, and I assume it's related.

**Comment by sandreas** [comment]
I try to fix this in the next release.

**Comment by sandreas** [comment]
Well, investigating the code, I found something I completely forgot. If you name the cover `cover.front.jpg` it will be used as front cover.

While this is not fixing your issue, it may be interesting as a workaround. 


For the next release I'm not going to implement a new parameter style but just using the first cover as `FRONT`, the second as `BACK` and the third as `CD`, as long as the filename does not contain keywords.
Using `GENERIC` as default is not helpful at all.
