### ISSUE TITLE
Embedded Picture Invalid ID3 frame size..

### ISSUE THREAD

**Issue by gitoss** [sandreas/tone#56]
Embedding an image with "tone --meta-cover-file=image.jpg audio.mp3" works nicely, but Exiftool returns "Warning: Invalid ID3 frame size".

I've tried to pinpoint the problem on tone with mpg123-strip <in.mpg >out.mp3, tone.exe tag --meta-cover-file=image.jpg out.mp3

Using tone release 0.1.5 on Windows.

**Comment by sandreas** [comment]
Something to be discussed with the `atldotnet` maintainer... thanks for reporting.

**Comment by sandreas** [comment]
@gitoss 
Is this still happening with `tone 0.1.6`?

**Comment by sandreas** [comment]
tone `0.1.7` is out, no feedback - I'm going to assume this is fixed. Feel free to reopen the issue, if not.
