### ISSUE TITLE
Feature Request:  Copy from one field to another

### ISSUE THREAD

**Issue by jeff47** [sandreas/tone#65]
Thanks for your great work on this.

It would be useful to be able to copy from one field to another, particularly for audiobooks where the use of fields isn't exactly standard.  I find myself often wanting to create a "NARRATOR" field, and copy the contents of the "COMPOSER" field into it.  Likewise, an "AUTHOR" or "WRITER" field and copy in the contents of "ARTIST".

**Comment by sandreas** [comment]
Doesn't 

```
--meta-equate
```

work for your usecase?

If so, what would you expect?

**Comment by jeff47** [comment]
> Doesn't
> 
> ```
> --meta-equate
> ```
> 
> work for your usecase?
> 
I will try that -- but where is it documented?  How do I specify the field to copy from, and the field to copy into?

**Comment by sandreas** [comment]
> I will try that -- but where is it documented? 

Unfortunately, this seems to be missing except the fact that it exists... I'll try to fix that in the next documentation update.

> How do I specify the field to copy from, and the field to copy into?

Two possibilities:

* `--meta-equate="author,writer,composer"` - first field source, all further fields destination
* `--meta-equate="author" --meta-equate="writer" --meta-equate="composer" - first field source, all further fields destination

You can also mix these two approaches afaik (like `--meta-equate="author,writer" --meta-equate="composer"`).


 
As a reference, here are the fields that could be equated (assumed they have the same type):

```
    Album,
    AlbumArtist,
    Artist,
    Bpm,
    ChaptersTableDescription,
    Composer,
    Comment,
    Conductor,
    Copyright,
    Description,
    DiscNumber,
    DiscTotal,
    EncodedBy,
    EncoderSettings,
    EncodingTool,
    Genre,
    Group,
    ItunesCompilation,
    ItunesMediaType,
    ItunesPlayGap,
    LongDescription,
    Lyrics,
    Part,
    Movement,
    MovementName,
    Narrator,
    OriginalAlbum,
    OriginalArtist,
    Popularity,
    Publisher,
    PublishingDate,
    PurchaseDate,
    RecordingDate,
    SortTitle,
    SortAlbum,
    SortArtist,
    SortAlbumArtist,
    SortComposer,
    Subtitle,
    Title,
    TrackNumber,
    TrackTotal,
```

Unfortunately, additional properties (like `narrator`) will not work, as there is no mapping defined for this. Maybe this could be part of your feature request via assuming that every property name that could not be found is a custom property.

If you would like to have a quick working solution for your problem, you could also try to write a [small JavaScript Tagger](https://github.com/sandreas/tone?tab=readme-ov-file#custom-scripted-taggers-experimental):

```
// customEquate.js
function customEquate(metadata, parameters) {
    metadata.AdditionalFields["NARRATOR"] = metadata.Composer;
}
tone.RegisterTagger("customEquate");
```

Then:

```
tone tag "my-file.m4b" --taggers="customEquate" --script="customEquate.js" 
```

I'll try to think about a solution for this feature in the near future. Have fun :-)

**Comment by sandreas** [comment]
This will be better documented in the next release
