### ISSUE TITLE
Documentation request:  compile instructions

### ISSUE THREAD

**Issue by jeff47** [sandreas/tone#66]
Would it be possible for you to add compile instructions (linux?) in the readme?  Thanks.

**Comment by sandreas** [comment]
> Would it be possible for you to add compile instructions (linux?) in the readme? Thanks.

Sure. For reference to publish a binary (release mode):

```
dotnet publish tone/tone.csproj --framework net6.0 --runtime "linux-x64" -c Release -p:PublishSingleFile=true --self-contained true -p:PublishReadyToRun=true -p:PublishTrimmed=true -o "tone"
```

Otherwise just open the solution with e.g. JetBrains Rider or VS Code and Run `tone` project.

**Comment by sandreas** [comment]
Ok, added these into the latest readme, push will happen in the next days.
