### ISSUE TITLE
json output appears to be broken

### ISSUE THREAD

**Issue by BrianAker** [sandreas/tone#68]
In trying to use the output created by --format json  I run into the problem that they way in which tone generates multiline json is unsupported. The descriptions in books will come out like so when they are long:

  "description": "In pages bound with echoes deep,
Where stories rise, and shadows sleep,
Tone whispers soft, then boldly sings,
A book of color, sound, and wings.",

jq and other json tools will throw an error on that. A simple solution is just to replace all of the \r and \n, with \\r and \\n in the string. This problem exists for embeddedPictures.data as well.

Thank you for creating such a useful tool!

**Comment by sandreas** [comment]
Yeah this is a problem with a lib i did not find a solution for yet. 

Atm you could try to use --export as a partial workaround

**Comment by BrianAker** [comment]
The library appears to be using the value from COLUMNS to set max width when writing.  Setting it to something absurdly high might resolve it.

**Comment by sandreas** [comment]
> The library appears to be using the value from COLUMNS to set max width when writing. Setting it to something absurdly high might resolve it.

Yes, the author of the lib does not recommend to do so (but I did not found him giving a proper reason). His suggested solution is to use `Console.WriteLine` instead. See

https://github.com/spectreconsole/spectre.console/issues/845

**Comment by BrianAker** [comment]
Why not call isatty() and assume --export if you determine the output is being redirected?

I do see why the original author would not want to set a MAX column, it is not a portable solution, though the limitation being imposed by how Linux is handling it is a little blunt.

**Comment by sandreas** [comment]
I have to do some research because I would like `tone` to be cross platform.


Thank you for suggesting isatty() thats a good idea. Maybe this is something spectre.console could do automatically.

**Comment by BrianAker** [comment]
For .NET I did find this:

https://learn.microsoft.com/en-us/dotnet/api/system.console.isinputredirected?view=net-8.0

This wraps the POSIX isatty() calls on platforms that have it and does something similar for Windows. There was an earlier method was used ( which does work on OSX ), but it appears that the above library call works across platform.  You can see it at:

https://stackoverflow.com/questions/3453220/how-to-detect-if-console-in-stdin-has-been-redirected/12527552#12527552

**Comment by sandreas** [comment]
> For .NET I did find this:
> 
> https://learn.microsoft.com/en-us/dotnet/api/system.console.isinputredirected?view=net-8.0
> 
> This wraps the POSIX isatty() calls on platforms that have it and does something similar for Windows. There was an earlier method was used ( which does work on OSX ), but it appears that the above library call works across platform.  You can see it at:
> 
> https://stackoverflow.com/questions/3453220/how-to-detect-if-console-in-stdin-has-been-redirected/12527552#12527552

Thank you. Probably I will either
- use Console.WriteLine or
- set width to int.MaxValue if Console.IsInputRedirected

I'm gonna research which i like better.
