### ISSUE TITLE
Resizing covers

### ISSUE THREAD

**Issue by cavalrymargarine0x1** [sandreas/tone#73]
Hi, is it possible to resize covers with _tone_? I read through the --help and the README but couldn't find any info on resizing covers

`tone tag "C:\Test.opus" --meta-cover-file 400x400`, the output was:

`── unchanged: C:\Test.opus ────────────────────────────────────────────────`

Thanks!

**Comment by sandreas** [comment]
> Hi, is it possible to resize covers with tone?

No currently I think this is outside the scope of `tone` - which is mainly an audio tool. Although covers can be embedded, this is only seen as binary file.

For cross platform command line resizing of images I'd recommend `libvips` or `imagemagick`, which would deliver way better quality and performance.

**Comment by sandreas** [comment]
>  didn't know imagemagick could resize embedded music file covers directly?

Don't think so... I don't know a tool that can do so.

Usually the workflow is
- having an original cover within the audio folder (500x500 or bigger)
- create a small thumbnail (e.g. with imagick)
- embed it via an audio tool (e.g. tone)


Resizing inplace would probably result in very poor quality images
