### ISSUE TITLE
audio.metaFormat is not resolving value for m4b and m4a files, works with mp3

### ISSUE THREAD

**Issue by sguilly123** [sandreas/tone#76]
Tested working up to Tone 1.8, from 1.9 onwards m4b/m4a files are not resolving a value for audio.metaFormat

These are the expected returned values:

m4b = {mp4}
m4a = {mp4}
mp3 = {id3V23, id3V1}

**Comment by sandreas** [comment]
could you provide a command and a sample file to reproduce?

**Comment by sguilly123** [comment]
Sure, I have converted the previous uploaded file to a m4b.

[TestBookFolder-m4b.zip](https://github.com/user-attachments/files/18085697/TestBookFolder-m4b.zip)

**Comment by sandreas** [comment]
Should be fixed in today's `0.2.2`.

**Comment by sguilly123** [comment]
Confirmed working in v0.2.2, thanks.
