### ISSUE TITLE
Update to supported .NET version

### ISSUE THREAD

**Issue by jwillikers** [sandreas/tone#77]
.NET 6 is EOL. Would it be possible to update to version 8 or 9? I'm working on updating the NixOS package for `tone` and this came up, https://github.com/NixOS/nixpkgs/pull/364325.

**Comment by sandreas** [comment]
> .NET 6 is EOL. Would it be possible to update to version 8 or 9? I'm working on updating the NixOS package for tone and this came up, https://github.com/NixOS/nixpkgs/pull/364325.

Absolutely. I would have done this much earlier, but I had some issues with the github actions releasing the binaries - it did not work with dotnet 8.0 out of the box. I have to analyze this again but thanks for submitting an issue as reminder. Try to fix this asap, but may take a while, I know this was nasty and I already invested some time in it. Maybe it could also be a walk in the park - we'll see.

**Comment by sandreas** [comment]
Well, it seems to have worked now. That was easy... ;)

**Comment by sandreas** [comment]
@jwillikers There we have it: https://github.com/sandreas/tone/issues/77

Not so easy :-)

**Comment by sandreas** [comment]
I have to add some trimmer config as it seems. Spectre.Console is not made for trimming...

**Comment by sandreas** [comment]
Ok, should work now... let's hope `0.2.3` has no more build related issues
