### ISSUE TITLE
Tone 0.2.3 not working on Windows 10.

### ISSUE THREAD

**Issue by sguilly123** [sandreas/tone#78]
Just tried the latest release of Tone 2.3, it generates a JSON error when run via my PowerShell script. When running tone.exe from a Windows command prompt generates the following below, rather than providing the usage/examples/options/commands output.

```
Spectre.Console.Cli.CommandRuntimeException: Could not get settings type for command of type
'tone.Commands.DumpCommand'.
  at ConfiguredCommand Spectre.Console.Cli.ConfiguredCommand.FromType<TCommand>(string , bool )
  at ICommandConfigurator Spectre.Console.Cli.Configurator.AddCommand<TCommand>(string )
  at void Program.<>c__DisplayClass0_0.<<Main>$>b__9(IConfigurator config)
  at async Task<int> Program.<Main>$(string[] )
```

**Comment by sandreas** [comment]
> Just tried the latest release of Tone 2.3, it generates a JSON error when run via my PowerShell script. When running tone.exe from a Windows command prompt generates the following below, rather than providing the usage/examples/options/commands output.

Thanks for reporting. `tone 0.2.3` did not contain any significant changes - it's just a change to `net8.0`. For now keep using `0.2.2`, I'm going to check this and unrelease `0.2.3`.

**Comment by sandreas** [comment]
`0.2.3` should work now... feel free to reopen if something does not. Thanks again for reporting the problem.
